lightning_module: 
  _target_: lightning_vocoders.models.hifigan.lightning_module.HiFiGANLightningModule

generator:
  num_input_channels: 1024
  upsample_rates: [7,7,3,3]
  upsample_initial_channel: 512
  upsample_kernel_sizes: [15,15,7,7]
  resblock_dilation_sizes: [[1,3,5], [1,3,5], [1,3,5]]
  resblock_kernel_sizes: [3,7,11]
  resblock: "1"

optim:
  opt_g:
    _target_: torch.optim.AdamW
    lr: 0.0002
    betas: [0.8,0.99]
  opt_d:
    _target_: torch.optim.AdamW
    lr: 0.0002
    betas: [0.8,0.99]
  scheduler_g:
    _target_: torch.optim.lr_scheduler.ExponentialLR
    gamma: 0.999998
  scheduler_d:
    _target_: torch.optim.lr_scheduler.ExponentialLR
    gamma: 0.999998
adversarial_start_step: 10_000

loss:
  recons_coef: 45
  fm_mpd_coef: 1
  fm_msd_coef: 1
  g_mpd_coef: 1
  g_msd_coef: 1
logging_wav_samples: 10