_target_: lightning_vocoders.preprocessor.dataset.glob_wav_dataset.GlobWavDataset
roots: 
  - /mnt/hdd/datasets/LJSpeech-1.1
  - /mnt/hdd/datasets/VCTK-Corpus
  - /mnt/hdd/datasets/libritts/libritts/LibriTTS/train-clean-100
  - /mnt/hdd/datasets/libritts/libritts/LibriTTS/train-clean-360
patterns: 
  - "**/*.wav"
  - "**/*.wav"
  - "**/*.wav"
  - "**/*.wav"